<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http:s//www.ros.org/wiki/xacro">

    <xacro:property name="arm_base_width" value="0.1" />
    <xacro:property name="arm_base_height" value="0.02" />

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="0.1 ${arm_base_width} 0.02" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.1 0.1 0.02" />
            </geometry>
        </collision>
        <xacro:box_inertia m="0.5" l="0.1" w="0.1" h="0.02" xyz="0 0 0" rpy="0 0 0" />
    </link>

    <link name="base_footprint">
    </link>

    <joint name="base_arm_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="arm_base_link" />
        <origin xyz="0 0 ${arm_base_height / 2}" rpy="0 0 0" />
    </joint>

</robot>