<?xml version="1.0"?>
<robot name="arm" xmlns:xacro="http:s//www.ros.org/wiki/xacro">

    <xacro:include filename="common_properties.xacro" />
    <xacro:include filename="arm.xacro" />

    <xacro:property name="length_of_arm" value="0.3" />
    <link name="forearm_link">
        <visual>
            <geometry>
                <cylinder radius="0.02" length="${length_of_arm}" />
            </geometry>
            <origin xyz="0 0 ${arm_base_height / 2}" rpy="0 0 0" />
            <material name="yellow" />
        </visual>
    </link>

    <link name="hand_link">
        <visual>
            <geometry>
                <cylinder radius="0.02" length="${length_of_arm}" />
            </geometry>
            <origin xyz="0 0 ${(length_of_arm + arm_base_height) / 2}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
    </link>

    <joint name="arm_base_forearm_joint" type="revolute">
        <parent link="arm_base_link" />
        <child link="forearm_link" />
        <origin xyz="0 0 ${length_of_arm / 2}" rpy="0 0 0" />
        <limit lower="0" upper="${pi / 2}" effort="100" velocity="100" />
        <dynamics friction="0.05" damping="0.1" />
    </joint>

    <joint name="forearm_hand_joint" type="revolute" >
        <parent link="forearm_link" />
        <child link="hand_link" />
        <origin xyz="0 0 ${length_of_arm / 2}" rpy="0 0 0" />
        <limit lower="0" upper="${pi / 2}" effort="100" velocity="100" />
        <dynamics friction="0.05" damping="0.1" />
    </joint>

</robot>